services:
  redis:
    image: redis:7.2.4-alpine3.19
    environment: 
      - TZ=America/New_York
    hostname: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      # Change the host port if there is a conflict
      - ${REDIS_PORT:-6379}:6379/tcp
    volumes:
      - "./redis-data:/data"
      - "./redis-conf:/usr/local/etc/redis:ro"
    restart: always
    volumes_from:
    - tmp
    depends_on:
      - tmp
  unbound:
    image: crazymax/unbound:1.19.3
    hostname: unbound
    environment: 
      - TZ=America/New_York
    depends_on:
      - redis
      - tmp
    volumes:
      - "./unbound-config:/config:ro"
      - "./unbound-keys:/etc/unbound/keys"
    restart: always
    expose:
      - "5053"
    volumes_from:
      - tmp
  tmp:
      image: busybox:1.36.1
      command: chmod -R 777 /tmp/docker
      volumes:
          - /tmp/docker        
  adguardhome:
      image: adguard/adguardhome:beta
      hostname: adguardhome
      environment: 
        - TZ=America/New_York
      ports:
        - 53:53/tcp
        - 53:53/udp
        - 784:784/udp
        - 853:853/tcp
        - 3002:3000/tcp
        - 80:80/tcp
        - 443:443/tcp
      volumes:
        - ./adguardhome-workdir:/opt/adguardhome/work
        - ./adguardhome-confdir:/opt/adguardhome/conf
      depends_on:
        - unbound
      restart: unless-stopped
      dns:
        - 8.8.8.8